#!/bin/bash
EXECUTABLE=approx.o
ALPHA=1
CTLG=100
LOAD=1 #Per each client
ITERATIONS=1000

echo ./$EXECUTABLE $ALPHA $CTLG $LOAD $ITERATIONS

./$EXECUTABLE $ALPHA $CTLG $LOAD $ITERATIONS > /tmp/log.log
